swagger: "2.0"

info:
  title: "Hello World Example"
  version: "1.0"

basePath: /v1.0

paths:
  /hello:
    get:
      summary: Generate greeting
      description: Generates a greeting message.
      operationId: server.hello_world
      produces:
        - text/plain;
      responses:
        200:
          description: greeting response
          schema:
            type: string
          examples:
            "text/plain": "Hello John"